---
apiVersion: v1
kind: Namespace
metadata:
  name: cfgmgmt
---
apiVersion: v1
kind: Service
metadata:
  namespace: cfgmgmt
  name: service
spec:
  selector:
    name: app
  ports:
    - port: 8080
      nodePort: 30005
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  namespace: cfgmgmt
  name: application
  labels:
    name: app
spec:
  containers:
    - name: config-mgmt
      image: configmgmt:1.0.0
      envFrom:
        - configMapRef:
            name: banner-config-stg
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: banner-config-stg
  namespace: cfgmgmt
data:
  app.env.label: Staging
  app.env.color: orange